addSbtPlugin("org.ensime" % "sbt-ensime" % "2.+")
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.+")
addSbtPlugin("org.duhemm" % "sbt-errors-summary" % "0.6.+")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.4.+")
addSbtPlugin("com.typesafe.sbt" % "sbt-license-report" % "1.2.+")
addSbtPlugin("com.softwaremill.clippy" % "plugin-sbt" % "0.6.+")
